sudo: true
dist: trusty
language: java
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGNIZATION
    token: $SONAR_TOKEN
jdk:
  - oraclejdk8
script:
  - Xvfb :5 -screen 0 800x600x24 &
  - export DISPLAY=:5
  - mvn --quiet clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - ls -la natural-language-processing/interview-cli/target/
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
